# Generated by Django 6.0.4 on 2026-04-09 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название курса", max_length=200, verbose_name="Название курса"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите превью курса",
                        null=True,
                        upload_to="courses/previews/",
                        verbose_name="Превью курса",
                    ),
                ),
                ("description", models.TextField(help_text="Заполните описание курса", verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название урока", max_length=200, verbose_name="Название урока"
                    ),
                ),
                ("description", models.TextField(help_text="Заполните описание урока", verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите превью урока",
                        null=True,
                        upload_to="lessons/previews/",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Укажите ссылку на видео", null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="lms.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
